### ISSUE TITLE
fed, stl: Very slow response for simple query (networks in text format)

### ISSUE THREAD

**Issue by javiquinte** [EIDA/mediatorws#35] opened 2018-06-21 10:18 UTC
The same query as in #28 . The timeout is not there anymore, because the Federator is streaming. Great.
However, the performance is quite poor.
It took almost **7 minutes** to return the list of networks in the format.
If I query the endpoints directly the answer comes in less than 1 second! (total time).
> javier@sec24c79:~/git/fdsnws_scripts$ curl "http://federator-testing.ethz.ch/fdsnws/station/1/query?level=network&format=text" -o ~/delete.me
>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
> 100 14879    0 14879    0     0     36      0 --:--:--  0:06:42 --:--:--     0

**Comment by Jollyfant** [comment] 2018-06-21 11:10
This is a symptom of #32 right?

Quote from #30:

> Resolving requests to the channel level is not feasible for inventories. You cannot make over 40000 requests to the endpoints to collect information on all channels in EIDA. Even at 130 requests per second it will take you 5 minutes.

Math seems to check out :-)

**Comment by damb** [comment] 2018-06-21 11:41
@Jollyfant,
for `level=channel` you calculation is right. However, for `level=station|network` we already implemented a *level reduction mechanism* i.e. if you request `fdsnws/station/1/query?level=network` `eida-federator` exclusively sends one request/network code (for `fdsnws/station/1/query?level=station` one request/sta code). In those cases a *granular approach* should be feasible.

`level=channel` we discuss in #30 and #32.

cheers

**Comment by kaestli** [comment] 2018-06-21 15:00
True that the throughput of our (eida.ethz.ch) fdsn/station implementation is at ~125-130 requests/second...
The current implementation
- does the same level of job fragmentation, parallelization & detailed logging for all types of services, and independent of the response format. This leads to simple code and consistent response
- it avoids analysis of the endpoint response (e.g. parsing and intelligent restructuring of xml trees for fdsn/station), thus keeps the cpu and memory requirements for the federator minimal. 

Both design decisions lead to the fact that some further optimizations possible for fdsnws/station, if used with text format, are not applied. If this turns out to be a strong showstopper, we should consider to change this (and pay for it with different logging granularity depending on whether text or xml is requested, and potentially with different caches used). If the homogeneous processing is feasible (although not optimal for some specific cases), i would rather prefer sticking to it.

**Comment by javiquinte** [comment] 2018-06-22 11:38
Please, @damb . I wrote to the EIDA mailing list but there was no answer yet. Could you tell us which are the nodes that are blacklisting the Federator? And apart from that, do you know why?
Are they just not answering (timeout) or are nodes that take a lot of time? Details could be of great help.

**Comment by damb** [comment] 2018-06-22 12:43
> Are they just not answering (timeout) or are nodes that take a lot of time? Details could be of great help.

We talk about:
  * timeouts (e.g. INGV)
  * slow responses (e.g. NOA)
  * requests are only responded partially (e.g. GFZ)

I'm going to provide a complete list which EIDA-Nodes are affected.



On 04:38 Fri 22 Jun     , Javier Quinteros wrote:
> Please, @damb . I wrote to the EIDA mailing list but there was no answer yet. Could you tell us which are the nodes that are blacklisting the Federator? And apart from that, do you know why?
> Are they just not answering (timeout) or are nodes that take a lot of time? Details could be of great help.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/EIDA/mediatorws/issues/35#issuecomment-399413636

-- 
| Daniel Armbruster
| ETH Zürich - Schweizer Erdbebendienst (SED)
| Email: daniel.armbruster@sed.ethz.ch
| Phone: +41 44 633 24 80
| Sonneggstrasse 5
| 8092 Zürich
| Switzerland


gpg --keyserver keys.gnupg.net --recv-key EF60F5CC

**Comment by damb** [comment] 2018-09-26 08:59
Duplicate of #35.

**Closed by damb** 2018-09-26 08:59 UTC
Labels: duplicate, enhancement
